export enum NotificationType {
  ENROLLMENT = 'ENROLLMENT',
  VIDEO = 'VIDEO',
  NOTES = 'NOTES',
  ASSIGNMENT = 'ASSIGNMENT',
  EXAM = 'EXAM',
  CERTIFICATE = 'CERTIFICATE',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  COURSE_APPROVED = 'COURSE_APPROVED',
  COURSE_REJECTED = 'COURSE_REJECTED',
  SYSTEM = 'SYSTEM',
}